### ISSUE TITLE
Compilation error with GNAT GPL 2017

### ISSUE THREAD

**Issue by stangassinger** [AdaCore/SPARK_Railway_Simulation_Demo#1]
i checked out the example code and did how described in the readme.
i got this error message:
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
gprbuild --target=arm-eabi -d -P/home/tux/spark_railway_demo/SPARK_Railway_Simulation_Demo/spark_railway_demo.gpr -XBUILD=Debug -XLCH=led -XRTS=ravenscar-sfp -XLOADER=ROM /home/tux/spark_railway_demo/SPARK_Railway_Simulation_Demo/src/train_demo.adb -largs -Wl,-Map=map.txt
Compile
   [Ada]          train_demo.adb
driver.ads:31:04: too many arguments in call to "Create_Restricted_Task"
gprbuild: *** compilation phase failed
[2017-06-20 19:44:13] process exited with status 4, 0% (1/216), elapsed time: 02.28s
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
I have the downloaded and installed the actual gps 2017 for arm
Maybe i am missing something.
i am new to ada

**Comment by Fabien-Chouteau** [comment]
Hi,

We did not ported this demo to the new GNAT GPL 2017 release yet. We recommend to use the 2016 release that is still available at [http://libre.adacore.com/download/configurations](http://libre.adacore.com/download/configurations).

Regards,

**Comment by Fabien-Chouteau** [comment]
Hello @stangassinger,

We've just updated this demo for GNAT GPL 2017. Give it a try and don't hesitate to tell us if it doesn't work.

Regards,

**Comment by aogrcs** [comment]
Dear @ Fabien,
Does this demo support for GNAT GPL 2019 now? GNAT for ARM Package means gnat-gpl-2017-arm-elf-windows-bin.exe? Is this right? Do you have any trivial example for Raspberry pi like tutorial? Thanks!
Sincerely

**Comment by aogrcs** [comment]
Dear @Fabien-Chouteau ,
Does this demo support for GNAT GPL 2019 now? GNAT for ARM Package means gnat-gpl-2017-arm-elf-windows-bin.exe? Is this right? Do you have any trivial example for Raspberry pi like tutorial? Thanks!
Sincerely

**Comment by Fabien-Chouteau** [comment]
Hello @aogrcs ,

I just checked with GNAT GPL 2019 and it seems to work fine.

I don't think we have examples specifically for the Raspberry Pi, but you can install the compiler from your Linux distribution `apt install gnat gprbuild` and then, for instance, follow the examples of our learning website: [learn.adacore.com](learn.adacore.com).

**Comment by aogrcs** [comment]
Hello @Fabien-Chouteau,
What's the use of gnat-community-2019-20190517-arm-elf-darwin-bin.dmg?
What's the mean of GNAT for ARM Package?
Thanks!

**Comment by Fabien-Chouteau** [comment]
I am not familiar with MacOs, but the this is the installation package for the compiler.

**Comment by aogrcs** [comment]
Hi @Fabien-Chouteau,
The ARM ELF means cross compiler hosting on different platform, is this right! Thanks

**Comment by Fabien-Chouteau** [comment]
Yes it is the cross compiler.

**Comment by aogrcs** [comment]
Thanks! @Fabien-Chouteau

**Comment by BrianRodas** [comment]
Hola, soy nuevo en ada y justo estoy haciendo mi primer Hola Mundo, al momento de ejecutar me aparece esto:
Executing task: gprbuild -p -gnatef hello_world.gpr <

Setup
   [mkdir]        object directory for project Hello_World
Compile
   [Ada]          hello_world.adb
gprbuild: *** compilation phase failed
The terminal process "C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -Command gprbuild -p -gnatef hello_world.gpr" terminated with exit code: 1.

Terminal will be reused by tasks, press any key to close it.
