### ISSUE TITLE
Sources for Raspberry Pi version

### ISSUE THREAD

**Issue by wollud1969** [AdaCore/SPARK_Railway_Simulation_Demo#2]
In the talk at FOSDEM 16 (https://archive.fosdem.org/2016/schedule/event/ada_raspberry/) a Raspberry Pi version of the train control project is mentioned. I'm searching for a non-trivial example of Ada code for the Raspberry Pi, so I was happy to find this talk. Unfortunately I can't find the sources. Can you provide them?

Cheers,
Wolfgang

**Comment by Fabien-Chouteau** [comment]
Hello,

The sources for this project are not online yet and I don't think we have another demo for the Rasoberry Pi. It's a native platform, so you should be able to get a GNAT compiler from the distribution and start programming right away.

To try Ada for embedded, I would recommend getting one of the the cheap STM32F4 disco board and try one of the examples in the [Ada_Drivers_Library](https://github.com/AdaCore/Ada_Drivers_Library/tree/master/examples) project.

Regards,
