### ISSUE TITLE
Can't find st-flash

### ISSUE THREAD

**Issue by GlenFlint** [AdaCore/SPARK_Railway_Simulation_Demo#3]
[log.txt](https://github.com/AdaCore/SPARK_Railway_Simulation_Demo/files/2369187/log.txt)

Where can I find the st-flash utility to load the program into the Discovery Card?

**Comment by Fabien-Chouteau** [comment]
Hi @GlenFlint ,

You have to build it from the sources: https://github.com/texane/stlink
Instructions are here: https://github.com/texane/stlink/blob/master/doc/compiling.md

Best regards,

**Comment by GlenFlint** [comment]
Thank you!  It's working now.  The readme.md says, "Please note that this project exists as part of a blog entry, article, or other similar material by AdaCore. "  Could you please direct me to the blog entry or article?

**Comment by Fabien-Chouteau** [comment]
You are welcome :)

The text in the README is a generic disclaimer that we put in our demo repositories.
Unfortunately there's no blog post associated with this project. You can still have a look at our blog. I am sure you will fund other interesting projects: blog.adacore.com

Regards,
